services:
  - type: web
    name: hanv-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: BOT_URL
        sync: false
